### ISSUE TITLE
Example of how to use "rtmpdump -W"

### ISSUE THREAD

**Issue by ionatan-israel** [LeonardoCiaccio/GrabAnyMedia#1]
I have this string: "https://player.vzaar.com/player/14.1.0.40/vz_player.swf?account_type_id=90&id=8756018&guid=vz2ba990b4e8fc41749d4a1da933e17502&ts=20170228125210&hs=6b62df0de945dd0698686f019cf0f5ed&home_path=http%3A%2F%2Fvzaar.com&w=1280&h=720&format=mp4&duration=502.01&gatracking=UA-76863-17&userID=135255&playlist_mode=bottom&hideFullscreen=false&colourSet=black&d=1"

@LeonardoCiaccio, That I have to do?  Examples?

**Comment by LeonardoCiaccio** [comment]
https://www.youtube.com/watch?v=kkc5_KwU8qQ&index=11&list=PLISSxErRXU1P_j0kTKZr2HL9KlT3vsOjK
