### ISSUE TITLE
Not working on last Chrome (ver. 65.0.3325.146 (Official Build) (64 bit)

### ISSUE THREAD

**Issue by MarkoIndaco** [LeonardoCiaccio/GrabAnyMedia#10]
Hi, as title it doesn't work on last Chrome release. The error message is: **File manifest missing or illegible**.

**Comment by LeonardoCiaccio** [comment]
work fine, drag&drop Extension folder, watch this tutorial
https://www.youtube.com/watch?v=9bDzzWiA4fk

2018-03-10 19:40 GMT+01:00 Marko <notifications@github.com>:
