### ISSUE TITLE
Enhancement for GrabAnyMedia popup window

### ISSUE THREAD

**Issue by Peuj** [LeonardoCiaccio/GrabAnyMedia#12]
Hi,

Most of the time, when I use GrabAnyMedia, I click on the GrabAnyMedia button which open a popup window then I click on "Copy" or select the wanted link then click on "Copy" and finally I click on the Close button to close the popup window.

That makes a lot of clicks for a fairly simple action.
Of course I realize we don't all have the same use-cases but still.

1 - I think it could be easier if we could have, instead of the popup window, a popup panel which only shows what we see in the tab "Media" with an access to the popup window as advanced mode.
It can also be an option to choose the behavior (simple mode or advanced mode) when we click on the button.

2 - In the meantime what could be very good, is to be able to close the popup window by clicking anywhere outside the blue border. (see image below) .
It seems a normal behavior (for me) and also more convenient to use when you have a large screen or worth 2 large screens and you need to click far on the top right to close the popup window.
![gam](https://user-images.githubusercontent.com/6862131/41103996-bbf8ab7c-6a6a-11e8-83d3-45047b097d9d.jpg)

Thanks

**Comment by LeonardoCiaccio** [comment]
hi @Peuj ,
all action have a scope, enjoy !
