### ISSUE TITLE
clyp it

### ISSUE THREAD

**Issue by rayman89** [LeonardoCiaccio/GrabAnyMedia#13]
When using it on the site ex link https://clyp.it/b04p1odi?token=b0078e077e15835845c528a44417719d the addon finds the file but clicking on download does nothing. Playing on preview shows an other download option but when clicking on it says play the video first or analyze i tried doing both and i still get the same error. I'm able to copy the link though and download it using the save link as... but the download it's not working otherwise.

**Comment by LeonardoCiaccio** [comment]
![immagine](https://user-images.githubusercontent.com/1698144/43788923-f3555910-9a6e-11e8-9de0-61d5038eead4.png)

**Comment by rayman89** [comment]
I updated the url https://clyp.it/b04p1odi?token=b0078e077e15835845c528a44417719d the link should be working now

**Comment by LeonardoCiaccio** [comment]
![immagine](https://user-images.githubusercontent.com/1698144/43789281-d38af9e0-9a6f-11e8-8101-779aa3a9e63a.png)

**Comment by rayman89** [comment]
... come on man if there is a download button there why are you telling me that? Shouldn't the download button start the download? The point is not me getting the song. I already got it like I said on the first post.

**Comment by LeonardoCiaccio** [comment]
the biggest mistake a user makes is to think that all the sites are the same ...

**Comment by rayman89** [comment]
I know they all don't work the same that's why I report it so you could fix it if you are interested in doing it. Also it would be nice if you could let the user know that something happened like for example in this cases that the button does not work show a message displaying "Currently Grab Any Media does not support download trough the addon on this site. Please copy the url address and paste it on a download manager to get the file" or something like that.

**Comment by LeonardoCiaccio** [comment]
for this reason the buttons have been added : **Preview** / **Open** / **Copy**

**Comment by rayman89** [comment]
OK sorry it's clear that you don't want to work on fixing/improving this I won't post anymore.
