### ISSUE TITLE
Feature request: Option to disble the blue button that pops up on streaming video window

### ISSUE THREAD

**Issue by vortexnix** [LeonardoCiaccio/GrabAnyMedia#14]
Thank you for the great extension. I love it. I mainly use it by clicking on the small blue button provided in the Firefox toolbar and then copying the desired link to download it. 

My only qualm is that whenever I hover over a video, the blue button pops up on its own and pauses the streaming video. This is undesirable behavior at least for me. Also, in some of the emby sites, the blue button pops up right over another button and that another button cannot be used anymore. 

Kindly provide an option to disable the blue button that pops up automatically on the streaming video. Thank you.

**Comment by LeonardoCiaccio** [comment]
Hi @vortexnix ,
i can't develop this option, i want my logo on all player 😉
Anyway, we develop a version Premium without this feature, stay tuned ...
