### ISSUE TITLE
incompatibility (on firefox) with url steam

### ISSUE THREAD

**Issue by littleboy62** [LeonardoCiaccio/GrabAnyMedia#15]
Yo everyone.

I noticed a little incompatibility, on firerfox, by going the steam website...
Example of url : https://store.steampowered.com/app/1091400/Online_Simulator/

If the addon is enabled, i can't click on different pictures / videos, nothing happens.
If the addon is disabled, i can do it.

I made a short video of this incompatibility : https://streamable.com/gj6jf

Looks like it's blocking the left click (maybe).

Have a nice day.
See you.

nb : There may be mistakes, because i'm french. If so, sorry.

**Comment by LeonardoCiaccio** [comment]
Hi @littleboy62 

i found this issue on load addon and not loaded from GAM, issue from page not addon : 

![immagine](https://user-images.githubusercontent.com/1698144/59607201-2c96d780-9113-11e9-92e2-df4ceeb320c5.png)
