### ISSUE TITLE
Breaks Slack in Firefox Developer Edition

### ISSUE THREAD

**Issue by irasanchez** [LeonardoCiaccio/GrabAnyMedia#17]
Causes Slack web app to engage in an endless refresh loop.

**Comment by LeonardoCiaccio** [comment]
Tested now, all feature work fine Slack & GAM, check other plugins for your issue

**Comment by irasanchez** [comment]
Hm, I disabled all of my add-ons and when this one was enabled by itself, the loop happened. I'll keep tinkering. Thanks!
