### ISSUE TITLE
No good way to download Twitter Videos

### ISSUE THREAD

**Issue by mosajjal** [LeonardoCiaccio/GrabAnyMedia#2]
Hi. Is there a way to make downloading from Twitter a bit easier? As of now, GrabAnyMedia can download "chunks" of Video in multiple files but not the whole video.

thanks

**Comment by LeonardoCiaccio** [comment]
https://www.youtube.com/watch?v=BdGzCepLYoA

**Comment by mosajjal** [comment]
Thank you so much for taking the time. And thank you SO MUCH for picking that video #amala

for linux users, after copying the `m3u8` file, they can use this command to get the video:

`ffmpeg -i m3u8_FILE -c copy out.mp4`

example(the Inter birthday video):

`ffmpeg -i https://video.twimg.com/amplify_video/839599601388818432/pl/Fl7yaT-muP5fdJyI.m3u8 -c copy inter_birthday.mp4`
