### ISSUE TITLE
Javascript

### ISSUE THREAD

**Issue by trimechee** [LeonardoCiaccio/GrabAnyMedia#23]
Hello, i find the review  videohelp : 
"Been using this for a while. On the whole it does a great job. That was until a few days ago, when it was flagged for going to a malicious site. I questioned it and got this response We've blocked this page as it loads an external resource
from bodelen[.]com. This is a domain we associate with malicious JavaScript, please see
https://www.pcrisk.com/removal-guides/14417-bodelen-com-pop-up-redirect
This is being loaded via the following code which is visible in the source:

Please would you therfore respond and sort this out

Thank You"

**Comment by LeonardoCiaccio** [comment]
I made some changes and updated the jQuery library to ensure the resolution of the latest vulnerabilities. I invite you to check if you are using the latest updated version.

**Comment by trimechee** [comment]
Great ! Thank you :) 🥇
