### ISSUE TITLE
Compatibilità estensione + Supporto a siti di adult live streaming?

### ISSUE THREAD

**Issue by Warmuser** [LeonardoCiaccio/GrabAnyMedia#5]
Ciao Leonardo, complimenti per la fantastica estensione! Ho aperto questo post per riferirti che ho provato ad utilizzare la tua estensione da Chrome aggiornato all' ultima versione e mi segnala che l' estensione non è pacchettizzata. Non so se questo interferirà con gli eventuali nuovi aggiornamenti perché ultimamente il Browser tende a nascondere le estensioni non aggiornate. Quindi ho pensato che fosse doveroso metterti al corrente della cosa. Ma tralasciando fatto, l' estensione non riesce a provvedere dei collegamenti validi quando la utilizzo per estrapolare live streaming di cams su siti adulti come per esempio xhamsterlive & chaturbate. 

Col primo non ci sono riuscito in nessun caso, col secondo invece si, ma utilizzando un collegamento finalizzato per Apple (mi pare fosse Itunes) ma non ho ben capito se fossero pacchetti già scaricati dato che lo streaming su VLC non andava di pari passo con la pagina aperta sul Browser. In più se sceglievo di mutare il video, lo streaming su VLC si bloccava. Dopo si è fermato del tutto nonostante avessi la pagina ancora a aperta ed avessi tolto il muto e provato ad aggiornare si la pagina che il link. 

Effettivamente non so se l' estensione è stata concepita per questi propositi, spero di si ahah. Comunque sarebbe possibile aggiungere i siti che elencherò? Possibilmente non confinando la focalizzandosi sul dominio "it" non sia mai provando ad accedere da diverse locazioni, non sia possibile poi avviare lo stream. 

https://it.chaturbate.com
https://it.xhamsterlive.com
https://it.cam4.com

PS: Ho notato anche che l' estensione tende a creare molte copie di un ipotetico stesso collegamento. Per ex, VIDEO SWF ( per 'RTMPDump -W' ) con link esempio: http://linkcam.com/etc.. per moltissime volte consective. Sarebbe possibile filtrare la lista per evitare eventuali cloni? E se no, come mai servono? Grazie.

Cmq su chaturbate vanno i collegamenti per i M3U8 ma solo in maniera frammentata, cioè pochi secondi per ogni collegamento. Mentre i video TS non vanno mai in ogni sito dove cerco di fare streaming di cam su VLC. Inoltre se scarico gli M3U8 non partono ma generano errore.

**Comment by LeonardoCiaccio** [comment]
La versione Chrome non è pacchettizzata e va utilizzata in dev-mode.
Quando possibile disabilita il flash player e utilizza HTML5.

https://grabanymedia.chaturbate.com senza problemi

https://it.xhamsterlive.com con HTML5 puoi unire tutti i frammenti, i manifest sono criptati.

https://it.cam4.com tutto ok, con .m3u8, ne ricevi tanti perché è proprio un protocollo di comunicazione, il contenuto è ogni volta diverso, dinamico, cmq butta il primo in VLC e vai tranquillo, oppure utilizzando altre tecniche ad esempio con FFMPEG
 
`ffmpeg -i "il tuo link .m3u8" -c copy "GAM.video.mp4"`

**Comment by Warmuser** [comment]
Ok grazie per la velocissima risposta! :) Proverò e ti farò sapere.
