### ISSUE TITLE
Filtering  url's

### ISSUE THREAD

**Issue by DanaMW** [LeonardoCiaccio/GrabAnyMedia#6]
Not really an issue, was wondering if we might get a toggle (on/off)  for the url filtering this extension does. I have not been into the workings very far but i would be more comfortable if it scanned/filtered only when i need it  too. If you know what I mean.is something like that a possibility here?

**Comment by DanaMW** [comment]
I may have been mistaken. Does this only filter when you click the button? or is it always filtering URL's?

**Comment by LeonardoCiaccio** [comment]
Hi, u can set **Option** » **Size** » **Minimum size** to higher value for example **1 GB** and ignore all files **< 1 GB**
Thanks for using Grab Any Media , version 7 coming soon

**Comment by DanaMW** [comment]
Ok. Just to question i would be more inclined to disable the addon until I need it. So that is sort of  what I mean./ I would like to have it still on the toolbar but not preforming any functions that might slow the browser. Does it only scan URLS once you click the button? Or is it scanning all the while I browse?

**Comment by DanaMW** [comment]
Oh and your welcome,  really thank YOU nice work.

**Comment by LeonardoCiaccio** [comment]
This feature was present in previous versions, I had to remove it because the majority of users forgot it disabled and created problems, the impact on performance and still null

**Comment by LeonardoCiaccio** [comment]
It does not actually filter requests, just log them only after the user starts the extension he scans it, do not worry GAM is very fast and has no impact on the performance of the browser

**Comment by DanaMW** [comment]
Very good. Again Thank man for you work and help understanding.
