### ISSUE TITLE
Altering Facebook default behaviour 

### ISSUE THREAD

**Issue by DanaMW** [LeonardoCiaccio/GrabAnyMedia#7]
Firefox Developers 57 / happens on both Linux and windows.
When i play a video on Facebook in my timeline it plays poorly (plays sound in the background with the video froze) and your extension prevents the mini player that appears when you scroll the video off the screen from showing.  Also unable to pause the video.

**Comment by DanaMW** [comment]
Maybe a filter for exclude pages would be good.  And this would imply it is interacting with pages even when you dont bring it to the front. which is not something i would ever want in an extension of this type like we spoke about last night,

**Comment by LeonardoCiaccio** [comment]
Strange, please disable all extension and test GAM on Facebook, thanks


Il 14 Ott 2017 03:24, "Dana Meli" <notifications@github.com> ha scritto:

**Comment by LeonardoCiaccio** [comment]
Just tested, I do not have this problem on Facebook, Windows and Linux, please u can make a video with problem ?

**Comment by DanaMW** [comment]
Good evening, just arrived home and I will do that. I run fb purity and the css skin faceblack using stylus so i will start to see where the conflict is here in a bit and get back to you.

**Comment by DanaMW** [comment]
uBlock origin is the issue but only for your extension, when it is running. Everything works with your script disabled. Once enabled (your extension) the problem happens. Goes away when I toggle uBlock off or disable yours

**Comment by LeonardoCiaccio** [comment]
mmmm can't help "uBlock" users, add some filter in "uBlock" ?

**Comment by DanaMW** [comment]
uBlock is default install, meaning how it is set when you install it is how mine is currently. I guess i will try to log what is different with your extension in and with it out to see why it holds up the video with GAM installed
