### ISSUE TITLE
DailyMotion broken link button

### ISSUE THREAD

**Issue by MarkoIndaco** [LeonardoCiaccio/GrabAnyMedia#9]
Hi, as title post I found that in DailyMotion platform the button is broken (on Vivaldi browser)

![grabanymedia - broken link 1](https://user-images.githubusercontent.com/19596617/32573293-bc27d8cc-c4cd-11e7-9416-0ef8a5cd958a.png)

I also try with Chromium and it's worst. In this case the button won't show at all.

Regards

**Comment by LeonardoCiaccio** [comment]
yes, bug of webextension, move mouse over

**Comment by MarkoIndaco** [comment]
I try but nothing happens. When you move mouse over you can see the button gets highlight it, but no links are show, even clicking on it nothing happens

**Comment by LeonardoCiaccio** [comment]
only on Vivaldi ?

**Comment by MarkoIndaco** [comment]
Also with Chromium. I don't test Chrome, but I guess cuold be a DailyMotion issue, instead of GAM.
